In [1]:
import pandas as pd

# Woking with JSON

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.0384
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.6770
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.8340
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,3.8000
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,2.4700
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.2060
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-23,1790121601,0.2790

# Working with SQL

In [4]:
import sqlite3
import pandas as pd

In [5]:
conn = sqlite3.connect("test.db")

In [6]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS countrylanguage (
    CountryCode TEXT,
    Language TEXT,
    IsOfficial TEXT,
    Percentage REAL
)
""")

conn.commit()

In [7]:
data = [
    ("IND", "Hindi", "T", 43.6),
    ("IND", "English", "F", 12.2),
    ("USA", "English", "T", 86.2),
    ("FRA", "French", "T", 100.0)
]

cursor.executemany("""
INSERT INTO countrylanguage 
(CountryCode, Language, IsOfficial, Percentage)
VALUES (?, ?, ?, ?)
""", data)

conn.commit()

In [8]:
df = pd.read_sql_query("SELECT * FROM countrylanguage", conn)

In [9]:
df

   CountryCode Language IsOfficial  Percentage
0          IND    Hindi          T        43.6
1          IND  English          F        12.2
2          USA  English          T        86.2
3          FRA   French          T       100.0
4          IND    Hindi          T        43.6
5          IND  English          F        12.2
6          USA  English          T        86.2
7          FRA   French          T       100.0
8          IND    Hindi          T        43.6
9          IND  English          F        12.2
10         USA  English          T        86.2
11         FRA   French          T       100.0
12         IND    Hindi          T        43.6
13         IND  English          F        12.2
14         USA  English          T        86.2
15         FRA   French          T       100.0